version: '3'

networks:
  default:
     external:
        name: stuart

volumes:
  rabbit_data:
    external: true

services:
  rabbitmq:
    container_name: rabbit
    hostname: rabbit # required for rabbit config
    image: rabbitmq:3-management
    volumes:
      - rabbit_data:/var/lib/rabbitmq # persistence volume
    ports:
      - 5672:5672 # io
      - 15672:15672 # management