version: '3.1'

networks:
  default:
     external:
        name: stuart

volumes:
  mongo_data:
    external: true


services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db  # persistence volume
    ports:
      - 27017:27017
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: stuart
      ME_CONFIG_BASICAUTH_PASSWORD: password
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/