version: '3'
networks:
   default:
      external:
         name: stuart

volumes:
    sqlserver_data:
      external: true

services: 
  sqlserver:
    image: 'mcr.microsoft.com/mssql/server:latest'
    container_name: sqlserver
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1533:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssword$$

  # /var/lib/docker/volumes/sqlserver_data/_data
  # /VAR/OPT/MSSQL
  # sqlserver_data