version: '3'
networks:
   default:
      external:
         name: stuart

services: 
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=password
  pgadmin4:
    image: 'dpage/pgadmin4'
    container_name: pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=x@y.com
      - PGADMIN_DEFAULT_PASSWORD=1